#!/usr/bin/env bash

set -euo allexport pipefail

HOME="/tmp"
LD_LIBRARY_PATH="/opt/php74/lib:$LD_LIBRARY_PATH"
PATH="/opt/php74/bin:$PATH"
PHP_INI_SCAN_DIR="/opt/php74/etc/php.d"

composer run bootstrap
