---
name: build php versions

on:
  - push

jobs:
  php74:
    name: php74
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_PACKAGE=php74
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: datashaman/phial-runtime-7.4
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
