---
name: build php versions

on:
  - push

jobs:
  build-php74:
    name: php7.4 build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          build_args: PHP_PACKAGE=php74
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: datashaman/phial-runtime
          tags: build-php7.4
          username: ${{ secrets.DOCKER_USERNAME }}
