---
on:
  push:
    paths:
      - .github/workflows/php.yml
      - php/**

jobs:
  build-php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - php72
          - php73
          - php74
          - php80

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          repository: datashaman/phial-runtime
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: php
          build_args: PHP_PACKAGE=${{ matrix.php }}
          tags: build-${{ matrix.php }}
